# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/collector/profiles/v1development/profiles_service.proto

require 'google/protobuf'

require './opentelemetry/proto/profiles/v1development/profiles_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("opentelemetry/proto/collector/profiles/v1development/profiles_service.proto", :syntax => :proto3) do
    add_message "opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceRequest" do
      repeated :resource_profiles, :message, 1, "opentelemetry.proto.profiles.v1development.ResourceProfiles"
    end
    add_message "opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceResponse" do
      optional :partial_success, :message, 1, "opentelemetry.proto.collector.profiles.v1development.ExportProfilesPartialSuccess"
    end
    add_message "opentelemetry.proto.collector.profiles.v1development.ExportProfilesPartialSuccess" do
      optional :rejected_profiles, :int64, 1
      optional :error_message, :string, 2
    end
  end
end

module Opentelemetry
  module Proto
    module Collector
      module Profiles
        module V1development
          ExportProfilesServiceRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceRequest").msgclass
          ExportProfilesServiceResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.collector.profiles.v1development.ExportProfilesServiceResponse").msgclass
          ExportProfilesPartialSuccess = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.collector.profiles.v1development.ExportProfilesPartialSuccess").msgclass
        end
      end
    end
  end
end
