# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: opentelemetry/proto/profiles/v1development/profiles.proto

require 'google/protobuf'

require './opentelemetry/proto/common/v1/common_pb'
require './opentelemetry/proto/resource/v1/resource_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("opentelemetry/proto/profiles/v1development/profiles.proto", :syntax => :proto3) do
    add_message "opentelemetry.proto.profiles.v1development.ProfilesData" do
      repeated :resource_profiles, :message, 1, "opentelemetry.proto.profiles.v1development.ResourceProfiles"
    end
    add_message "opentelemetry.proto.profiles.v1development.ResourceProfiles" do
      optional :resource, :message, 1, "opentelemetry.proto.resource.v1.Resource"
      repeated :scope_profiles, :message, 2, "opentelemetry.proto.profiles.v1development.ScopeProfiles"
      optional :schema_url, :string, 3
    end
    add_message "opentelemetry.proto.profiles.v1development.ScopeProfiles" do
      optional :scope, :message, 1, "opentelemetry.proto.common.v1.InstrumentationScope"
      repeated :profiles, :message, 2, "opentelemetry.proto.profiles.v1development.Profile"
      optional :schema_url, :string, 3
    end
    add_message "opentelemetry.proto.profiles.v1development.Profile" do
      repeated :sample_type, :message, 1, "opentelemetry.proto.profiles.v1development.ValueType"
      repeated :sample, :message, 2, "opentelemetry.proto.profiles.v1development.Sample"
      repeated :mapping_table, :message, 3, "opentelemetry.proto.profiles.v1development.Mapping"
      repeated :location_table, :message, 4, "opentelemetry.proto.profiles.v1development.Location"
      repeated :location_indices, :int32, 5
      repeated :function_table, :message, 6, "opentelemetry.proto.profiles.v1development.Function"
      repeated :attribute_table, :message, 7, "opentelemetry.proto.common.v1.KeyValue"
      repeated :attribute_units, :message, 8, "opentelemetry.proto.profiles.v1development.AttributeUnit"
      repeated :link_table, :message, 9, "opentelemetry.proto.profiles.v1development.Link"
      repeated :string_table, :string, 10
      optional :time_nanos, :int64, 11
      optional :duration_nanos, :int64, 12
      optional :period_type, :message, 13, "opentelemetry.proto.profiles.v1development.ValueType"
      optional :period, :int64, 14
      repeated :comment_strindices, :int32, 15
      optional :default_sample_type_index, :int32, 16
      optional :profile_id, :bytes, 17
      optional :dropped_attributes_count, :uint32, 19
      optional :original_payload_format, :string, 20
      optional :original_payload, :bytes, 21
      repeated :attribute_indices, :int32, 22
    end
    add_message "opentelemetry.proto.profiles.v1development.AttributeUnit" do
      optional :attribute_key_strindex, :int32, 1
      optional :unit_strindex, :int32, 2
    end
    add_message "opentelemetry.proto.profiles.v1development.Link" do
      optional :trace_id, :bytes, 1
      optional :span_id, :bytes, 2
    end
    add_message "opentelemetry.proto.profiles.v1development.ValueType" do
      optional :type_strindex, :int32, 1
      optional :unit_strindex, :int32, 2
      optional :aggregation_temporality, :enum, 3, "opentelemetry.proto.profiles.v1development.AggregationTemporality"
    end
    add_message "opentelemetry.proto.profiles.v1development.Sample" do
      optional :locations_start_index, :int32, 1
      optional :locations_length, :int32, 2
      repeated :value, :int64, 3
      repeated :attribute_indices, :int32, 4
      proto3_optional :link_index, :int32, 5
      repeated :timestamps_unix_nano, :uint64, 6
    end
    add_message "opentelemetry.proto.profiles.v1development.Mapping" do
      optional :memory_start, :uint64, 1
      optional :memory_limit, :uint64, 2
      optional :file_offset, :uint64, 3
      optional :filename_strindex, :int32, 4
      repeated :attribute_indices, :int32, 5
      optional :has_functions, :bool, 6
      optional :has_filenames, :bool, 7
      optional :has_line_numbers, :bool, 8
      optional :has_inline_frames, :bool, 9
    end
    add_message "opentelemetry.proto.profiles.v1development.Location" do
      proto3_optional :mapping_index, :int32, 1
      optional :address, :uint64, 2
      repeated :line, :message, 3, "opentelemetry.proto.profiles.v1development.Line"
      optional :is_folded, :bool, 4
      repeated :attribute_indices, :int32, 5
    end
    add_message "opentelemetry.proto.profiles.v1development.Line" do
      optional :function_index, :int32, 1
      optional :line, :int64, 2
      optional :column, :int64, 3
    end
    add_message "opentelemetry.proto.profiles.v1development.Function" do
      optional :name_strindex, :int32, 1
      optional :system_name_strindex, :int32, 2
      optional :filename_strindex, :int32, 3
      optional :start_line, :int64, 4
    end
    add_enum "opentelemetry.proto.profiles.v1development.AggregationTemporality" do
      value :AGGREGATION_TEMPORALITY_UNSPECIFIED, 0
      value :AGGREGATION_TEMPORALITY_DELTA, 1
      value :AGGREGATION_TEMPORALITY_CUMULATIVE, 2
    end
  end
end

module Opentelemetry
  module Proto
    module Profiles
      module V1development
        ProfilesData = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.profiles.v1development.ProfilesData").msgclass
        ResourceProfiles = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.profiles.v1development.ResourceProfiles").msgclass
        ScopeProfiles = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.profiles.v1development.ScopeProfiles").msgclass
        Profile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.profiles.v1development.Profile").msgclass
        AttributeUnit = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.profiles.v1development.AttributeUnit").msgclass
        Link = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.profiles.v1development.Link").msgclass
        ValueType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.profiles.v1development.ValueType").msgclass
        Sample = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.profiles.v1development.Sample").msgclass
        Mapping = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.profiles.v1development.Mapping").msgclass
        Location = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.profiles.v1development.Location").msgclass
        Line = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.profiles.v1development.Line").msgclass
        Function = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.profiles.v1development.Function").msgclass
        AggregationTemporality = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("opentelemetry.proto.profiles.v1development.AggregationTemporality").enummodule
      end
    end
  end
end
